### ISSUE TITLE
Persistent MISP config

### ISSUE THREAD

**Issue by SHSauler** [Podictive/MISP-docker#1]
Hi @Podictive, thanks for your changes!

Like you mention in the README, a volume for persistent MISP settings would be neat! What's the disadvantage of just mounting the entire MISP folder? This would allow backups of all configs, artifacts etc. without having to know where they are located.

Like in XME's docker

```
      - /data/misp/web:/var/www/MISP
```
https://github.com/MISP/misp-docker/blob/master/docker-compose.yml#L13

Thanks!

**Comment by ChessSpider** [comment]
Hi SHSauler! Thanks !
At Podictive we have a CI/CD-pipeline which automatically rebuilds all docker images every week, to make sure the software and its dependencies are always the latest. For this to work well we need to separate the logic and the configuration.

With a [VOLUME /var/www/MISP](https://github.com/Podictive/MISP-docker/blob/master/Dockerfile#L142),  it also keeps the logic in a persistent state. Which requires the maintainer to do a manual `git pull` inside the container to update MISP. Which is not ideal, and something I'll have to change once we run MISP in production (so far its only for testing).

**Comment by SHSauler** [comment]
Makes sense, thanks for elaborating @ChessSpider!
